/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.CourseBLL;
import BLL.CourseInstructorBLL;
import BLL.PersonBLL;
import DTO.Course;
import DTO.CourseInstructor;
import DTO.Person;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class QuanLyPhanCongGiangDay extends javax.swing.JPanel {

    private int DEFALUT_WIDTH;
    private DefaultTableModel model;
    CourseInstructorBLL bll = new CourseInstructorBLL();
    public QuanLyPhanCongGiangDay() {
        this.setSize(1090, 750);
        initComponents();
    }

    public QuanLyPhanCongGiangDay(int width) throws Exception {
        DEFALUT_WIDTH = width;
        initComponents();
        this.setSize(this.DEFALUT_WIDTH - 200, 750);
        init();

    }

    private void init() throws Exception {
        ShowDataBase("ASC");
    }

    private void clearInput() {
        txID.setText("");
        txCourse.setText("");
        txTeacher.setText("");
    }

    private void ShowDataBase(String orderby) throws Exception {
        try {
            if (CourseInstructorBLL.getListCourseInstructor() == null) {
                bll.loadDSCourseInstructor(orderby);
            }
            insertHeader();
            outModel(model, CourseInstructorBLL.getListCourseInstructor());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không Thể Load Database ",
                    "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }
    private void RefreshDataBase(String orderby) throws Exception {
        try {
            bll.loadDSCourseInstructor(orderby);
            insertHeader();
            outModel(model, CourseInstructorBLL.getListCourseInstructor());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không Thể Load Database ",
                    "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }

  
    private void insertHeader() {
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã Khoá Học");
        header.add("Khoá Học");
        header.add("Mã Giảng Viên");
        header.add("Tên Giảng Viên");

        //if (model.getRowCount()==0)
        model = new DefaultTableModel(header, 0);

    }

    private void outModel(DefaultTableModel model, ArrayList<CourseInstructor> courseinstructor) // Xuất ra Table từ ArrayList
    {
        Vector data;
        model.setRowCount(0);
        for (CourseInstructor cs : courseinstructor) {
            data = new Vector();
            data.add(cs.getID());
            data.add(cs.getCourseID());
            data.add(cs.getTitleCourse());
            data.add(cs.getPersonID());
            data.add(cs.getTeacherName());

            model.addRow(data);
        }
        tbCourseInstructor.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCourseInstructor = new javax.swing.JTable();
        pInput = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txTeacher = new javax.swing.JTextField();
        btnSelectTeacher = new javax.swing.JButton();
        txCourse = new javax.swing.JTextField();
        btnSelectCourse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        pSearch = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbSelectSearch = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("PHÂN CÔNG GIẢNG DẠY");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(413, 413, 413))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        tbCourseInstructor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 0, 102), new java.awt.Color(0, 0, 0)));
        tbCourseInstructor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbCourseInstructor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCourseInstructor.setRowHeight(22);
        tbCourseInstructor.setSelectionBackground(new java.awt.Color(255, 204, 102));
        tbCourseInstructor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCourseInstructorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCourseInstructor);

        pInput.setBackground(new java.awt.Color(255, 255, 255));
        pInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INPUT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(153, 0, 0))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("KHOÁ HỌC");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("GIẢNG VIÊN");

        txTeacher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTeacherActionPerformed(evt);
            }
        });

        btnSelectTeacher.setBackground(new java.awt.Color(153, 153, 153));
        btnSelectTeacher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSelectTeacher.setText("...");
        btnSelectTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectTeacherActionPerformed(evt);
            }
        });

        txCourse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSelectCourse.setBackground(new java.awt.Color(153, 153, 153));
        btnSelectCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSelectCourse.setText("...");
        btnSelectCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCourseActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("MÃ PHÂN CÔNG:");

        txID.setEditable(false);
        txID.setBackground(new java.awt.Color(204, 222, 236));
        txID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout pInputLayout = new javax.swing.GroupLayout(pInput);
        pInput.setLayout(pInputLayout);
        pInputLayout.setHorizontalGroup(
            pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pInputLayout.createSequentialGroup()
                                .addComponent(txTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(btnSelectTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pInputLayout.createSequentialGroup()
                                .addComponent(txCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        pInputLayout.setVerticalGroup(
            pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txID, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSelectTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSelectCourse))
                    .addComponent(txTeacher))
                .addGap(25, 25, 25))
        );

        pSearch.setBackground(new java.awt.Color(255, 255, 255));
        pSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEARCH & FILTER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(0, 102, 0))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("CHỌN ĐIỀU KIỆN:");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSearch.setBackground(new java.awt.Color(255, 204, 0));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cbSelectSearch.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbSelectSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Khoá Học", "Mã Giảng Viên", "Tên Khoá Học", "Tên Giảng Viên" }));
        cbSelectSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSearchLayout = new javax.swing.GroupLayout(pSearch);
        pSearch.setLayout(pSearchLayout);
        pSearchLayout.setHorizontalGroup(
            pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSearchLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pSearchLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cbSelectSearch, 0, 96, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );
        pSearchLayout.setVerticalGroup(
            pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSelectSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(139, 139, 139))
        );

        btnDelete.setBackground(new java.awt.Color(153, 0, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("XOÁ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 51, 204));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("THÊM");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 153, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("SỬA");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRefesh.setBackground(new java.awt.Color(51, 51, 51));
        btnRefesh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefesh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefesh.setText("ReFresh");
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnRefeshActionPerformed(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefesh)
                        .addGap(18, 18, 18))
                    .addComponent(pInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefesh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1)))
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbCourseInstructorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCourseInstructorMouseClicked
        int i = tbCourseInstructor.getSelectedRow();
        if (i >= 0) {
            if (tbCourseInstructor.getRowSorter() != null) {
                i = tbCourseInstructor.getRowSorter().convertRowIndexToModel(i);
            }
            txID.setText(tbCourseInstructor.getModel().getValueAt(i, 0).toString());
            txCourse.setText(tbCourseInstructor.getModel().getValueAt(i, 1).toString());
            txTeacher.setText(tbCourseInstructor.getModel().getValueAt(i, 3).toString());

        }
    }//GEN-LAST:event_tbCourseInstructorMouseClicked
    private void Search() {
        DefaultTableModel temp = new DefaultTableModel();
        ArrayList<CourseInstructor> search = new ArrayList<>();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã Khoá Học");
        header.add("Khoá Học");
        header.add("Mã Giảng Viên");
        header.add("Tên Giảng Viên");
        String optionSearch=cbSelectSearch.getSelectedItem().toString();
       
        try {
            if(!txtSearch.getText().isEmpty()){
                 String inputSearch=txtSearch.getText();

                switch(optionSearch){
                    case "Mã Khoá Học":
                        search=bll.searchCourseID(Integer.parseInt(inputSearch));
                        break;
                    case "Mã Giảng Viên":
                        search=bll.searchTeacherID(Integer.parseInt(inputSearch));
                        break;
                    case "Tên Khoá Học":
                        search=bll.searchCourseTitle(inputSearch);
                        break;
                    case "Tên Giảng Viên":
                        search=bll.searchTeacherName(inputSearch);
                        break;
                    default:
                        break;
                }
            }
            else 
            JOptionPane.showMessageDialog(this, "Vui lòng nhập điều kiện tìm ", 
                    "Thông Báo", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không Thể Tìm Kiếm ", 
                    "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        if (search != null && search.size() > 0) {
            if (temp.getRowCount() == 0) {
                temp = new DefaultTableModel(header, 0);
            }
            for (int i = 0; i < search.size(); i++) {
                Vector row = new Vector();
                row.add(search.get(i).getID());
                row.add(search.get(i).getCourseID());
                row.add(search.get(i).getTitleCourse());
                row.add(search.get(i).getPersonID());
                row.add(search.get(i).getTeacherName());
                temp.addRow(row);
            }
            tbCourseInstructor.setModel(temp);
        }
    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn Thực Sự Muốn Xóa Phân Công Này ?",
                "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (confirm == 0)
        try {
            int teacherID = Integer.parseInt(txTeacher.getText());
            int courseID = Integer.parseInt(txCourse.getText());
            bll.deleteCourseInstructor(courseID, teacherID);//gọi Layer BLL xoá phân công     
            insertHeader();// chèn header cho table
            outModel(model, CourseInstructorBLL.getListCourseInstructor());// đổ data vào table
            clearInput();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Không thể xoá CourseInstructor ",
                    "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        } else
            return;
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        try {
            CourseInstructor csin = new CourseInstructor();
            csin.setCourseID((int) Integer.parseInt(txCourse.getText()));
            csin.setPersonID((int) Integer.parseInt(txTeacher.getText()));
            bll.addCourseInstructor(csin);// gọi Layer Bll Thêm phân công
            clearInput();
           RefreshDataBase("DESC");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Không thể tạo phân công giảng dạy ",
                    "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            int id = Integer.parseInt(txID.getText());
            int teacherID = Integer.parseInt(txTeacher.getText());
            int courseID = Integer.parseInt(txCourse.getText());
            CourseInstructor csin = new CourseInstructor();
            csin.setCourseID((int) courseID);
            csin.setPersonID((int) teacherID);
            // gọi Layer BLL cập nhật phân công
            bll.updateCourseInstructor(id, csin);
            clearInput();
            RefreshDataBase("DESC");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Không thể cập nhật CourseInstructor ",
                    "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSelectTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectTeacherActionPerformed
        JPFormPerson tbps;
        try {
            tbps = new JPFormPerson();
            int personID = tbps.getPersonID();// lấy ID Giảng viên từ Form chọn giảng viên
            txTeacher.setText(String.valueOf(personID));
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "Không thể tải lên danh sách giảng viên ",
                    "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSelectTeacherActionPerformed

    private void btnSelectCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCourseActionPerformed
        JPFormCourse tbcs;
        try {
            tbcs = new JPFormCourse();
            int courseID = tbcs.getCourseID();
            txCourse.setText(String.valueOf(courseID));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Không thể tải lên danh sách khoá học ",
                    "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSelectCourseActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       DefaultTableModel temp = new DefaultTableModel();
        ArrayList<CourseInstructor> search = new ArrayList<>();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã Khoá Học");
        header.add("Khoá Học");
        header.add("Mã Giảng Viên");
        header.add("Tên Giảng Viên");
        String optionSearch=cbSelectSearch.getSelectedItem().toString();
        try {
            if(!txtSearch.getText().isEmpty()){
                 String inputSearch=txtSearch.getText();
                switch(optionSearch){
                    case "Mã Khoá Học":
                        search=bll.searchCourseID(Integer.parseInt(inputSearch));
                        break;
                    case "Mã Giảng Viên":
                        search=bll.searchTeacherID(Integer.parseInt(inputSearch));
                        break;
                    case "Tên Khoá Học":
                        search=bll.searchCourseTitle(inputSearch);
                        break;
                    case "Tên Giảng Viên":
                        search=bll.searchTeacherName(inputSearch);
                        break;
                    default:
                        break;
                }
            }
            else 
            JOptionPane.showMessageDialog(this, "Vui lòng nhập điều kiện tìm ", 
                    "Thông Báo", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không Thể Tìm Kiếm ", 
                    "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        if (search != null && search.size() > 0) {
            if (temp.getRowCount() == 0) {
                temp = new DefaultTableModel(header, 0);
            }
            for (int i = 0; i < search.size(); i++) {
                Vector row = new Vector();
                row.add(search.get(i).getID());
                row.add(search.get(i).getCourseID());
                row.add(search.get(i).getTitleCourse());
                row.add(search.get(i).getPersonID());
                row.add(search.get(i).getTeacherName());
                temp.addRow(row);
            }
            tbCourseInstructor.setModel(temp);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnRefeshActionPerformed
         RefreshDataBase("ASC");
    }//GEN-LAST:event_btnRefeshActionPerformed

    private void txTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTeacherActionPerformed

    private void cbSelectSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelectSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelectCourse;
    private javax.swing.JButton btnSelectTeacher;
    private javax.swing.JComboBox<String> cbSelectSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pInput;
    private javax.swing.JPanel pSearch;
    private javax.swing.JTable tbCourseInstructor;
    private javax.swing.JTextField txCourse;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txTeacher;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
